### ISSUE TITLE
Load saved Datageometry object

### ISSUE THREAD

**Issue by jecaJeca** [ContextLab/hypertools-paper-notebooks#4]
Hello,

How can I make Datageometry object from saved Datageomatry object?  I would like to be able to see 3D figures after program finish.

Thanks!

**Comment by andrewheusser** [comment]
Hi!
```
import hypertools as hyp
geo.save('filename') # to save
geo = hyp.load('filename') # to load back in
```
http://hypertools.readthedocs.io/en/latest/tutorials/geo.html#saving-geos
